# Generated by Django 5.2.4 on 2025-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_add_message_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='access_url_name',
            field=models.CharField(max_length=100, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='display_url_name',
            field=models.CharField(max_length=100, blank=True, default=''),
        ),
    ]
