# Generated by Django 5.2.4 on 2025-07-24 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailWriterRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("business", "Business Email"),
                            ("follow_up", "Follow-up Email"),
                            ("complaint", "Complaint Email"),
                            ("thank_you", "Thank You Email"),
                            ("introduction", "Introduction Email"),
                            ("meeting_request", "Meeting Request"),
                            ("apology", "Apology Email"),
                            ("announcement", "Announcement"),
                        ],
                        help_text="Type of email to generate",
                        max_length=50,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Who the email is being sent to", max_length=200
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject (optional - can be auto-generated)",
                        max_length=200,
                    ),
                ),
                (
                    "main_message",
                    models.TextField(help_text="Main content/purpose of the email"),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("friendly", "Friendly"),
                            ("formal", "Formal"),
                            ("casual", "Casual"),
                        ],
                        default="professional",
                        help_text="Tone of the email",
                        max_length=30,
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("short", "Short (1-2 paragraphs)"),
                            ("medium", "Medium (3-4 paragraphs)"),
                            ("long", "Long (5+ paragraphs)"),
                        ],
                        default="medium",
                        help_text="Desired length of the email",
                        max_length=20,
                    ),
                ),
                (
                    "email_content",
                    models.TextField(blank=True, help_text="Generated email content"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Writer Request",
                "verbose_name_plural": "Email Writer Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
