# Generated by Django 5.2.4 on 2025-07-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyzer', '0001_initial'),
    ]

    operations = [
        # Add new fields only (don't remove old ones to avoid conflicts)
        migrations.AddField(
            model_name='dataanalysisagentrequest',
            name='data_file',
            field=models.FileField(blank=True, upload_to='uploads/data_analyzer/'),
        ),
        migrations.AddField(
            model_name='dataanalysisagentrequest',
            name='analysis_type',
            field=models.CharField(
                choices=[
                    ('summary', 'Summary Analysis'),
                    ('detailed', 'Detailed Analysis'),
                    ('statistical', 'Statistical Analysis'),
                ],
                default='summary',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='dataanalysisagentresponse',
            name='analysis_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dataanalysisagentresponse',
            name='insights_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataanalysisagentresponse',
            name='report_text',
            field=models.TextField(blank=True),
        ),
    ]