# Generated by Django 5.2.4 on 2025-07-10 04:31
# Modified to prevent duplicate column errors

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyzer', '0001_initial'),
    ]

    operations = [
        # No operations - fields already exist in database
        # This prevents "column already exists" errors during deployment
    ]