# Generated by Django 5.2.4 on 2025-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyzer', '0002_auto_20250710_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataanalysisagentrequest',
            name='input_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataanalysisagentresponse',
            name='output_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
