# Generated by Django 5.2.4 on 2025-07-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_analyzer", "0004_fix_duplicate_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataanalysisagentrequest",
            name="data_file",
            field=models.FileField(
                blank=True,
                help_text="PDF file for analysis",
                upload_to="uploads/data_analyzer/",
            ),
        ),
    ]
